import shutil
import sys
import tempfile
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from convert_to_docbook import REPO_ROOT  # noqa: E402

DB_NS = "{http://docbook.org/ns/docbook}"


class TestMigrateToNativeMetadata(unittest.TestCase):
    """Exercises the per-file migration pipeline (existing_title ->
    write_metadata -> insert_subtitle -> strip_sibling_title) directly --
    the same sequence main() runs per document -- rather than main()
    itself, which walks the *entire* real docs/ corpus via
    find_corpus_meta_files() with no way to scope it to one fixture
    file. Calling main() from a test would rewrite every real corpus
    .meta.xml as a side effect of running the test suite."""

    def setUp(self):
        self.tmp_dir = Path(tempfile.mkdtemp(dir=REPO_ROOT / "docs" / "wip"))
        self.addCleanup(shutil.rmtree, self.tmp_dir)
        self.meta_path = self.tmp_dir / "sample.meta.xml"
        self.xml_path = self.tmp_dir / "sample.xml"
        self.meta_path.write_text(
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            '<info xmlns="http://docbook.org/ns/docbook" '
            'xmlns:dc="http://purl.org/dc/terms/" '
            'xmlns:xi="http://www.w3.org/2001/XInclude">\n'
            '  <title>Sample Migrated Document</title>\n'
            '  <subtitle>A Hand-Authored Subtitle</subtitle>\n'
            '  <pubdate>2026-07-01</pubdate>\n'
            '  <biblioid class="uri">https://example.invalid/placeholder</biblioid>\n'
            '  <subjectset><subject><subjectterm>work in progress</subjectterm></subject></subjectset>\n'
            '  <publisher><publishername>metavacua/legal-theory (GitHub)</publishername></publisher>\n'
            '  <dc:type>Text</dc:type>\n'
            '  <xi:include href="../../common/authorgroup.xml" />\n'
            '  <xi:include href="../../common/legalnotice.xml" />\n'
            '</info>\n',
            encoding="utf-8",
        )
        self.xml_path.write_text(
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            '<article xmlns="http://docbook.org/ns/docbook" '
            'xmlns:xi="http://www.w3.org/2001/XInclude" '
            'version="5.2" xml:id="sample" xml:lang="en">\n'
            '  <title>Stale Sibling Title</title>\n'
            '  <xi:include href="sample.meta.xml" />\n'
            '  <para>Body content.</para>\n'
            '</article>\n',
            encoding="utf-8",
        )

    def _migrate_one(self, meta_path):
        """Reproduces main()'s per-file body exactly, scoped to one file."""
        from migrate_to_native_metadata import (
            existing_title, existing_subtitle, insert_subtitle,
            strip_sibling_title, content_path_for_meta,
        )
        from convert_to_docbook import write_metadata
        title = existing_title(meta_path)
        subtitle = existing_subtitle(meta_path)
        write_metadata(meta_path, title)
        if subtitle is not None:
            insert_subtitle(meta_path, subtitle)
        content_path = content_path_for_meta(meta_path)
        if content_path.exists():
            strip_sibling_title(content_path)

    def test_preserves_hand_authored_subtitle_across_rerun(self):
        # Regression test for the bug fixed in commit 0a1f2ed: re-running
        # used to silently drop <subtitle> because write_metadata() does
        # not itself emit one.
        self._migrate_one(self.meta_path)
        root = ET.parse(self.meta_path).getroot()
        title_el = root.find(f"{DB_NS}title")
        subtitle_el = root.find(f"{DB_NS}subtitle")
        self.assertEqual(title_el.text, "Sample Migrated Document")
        self.assertIsNotNone(subtitle_el, "subtitle was dropped on migration")
        self.assertEqual(subtitle_el.text, "A Hand-Authored Subtitle")
        self.assertEqual(list(root).index(subtitle_el), list(root).index(title_el) + 1)

        # Re-run a second time -- must still be present, not just surviving
        # the first pass by accident of file state before write_metadata
        # first touched it.
        self._migrate_one(self.meta_path)
        root2 = ET.parse(self.meta_path).getroot()
        subtitle_el2 = root2.find(f"{DB_NS}subtitle")
        self.assertIsNotNone(subtitle_el2, "subtitle was dropped on the SECOND run")
        self.assertEqual(subtitle_el2.text, "A Hand-Authored Subtitle")

    def test_dc_type_serializes_with_dc_prefix_not_an_autogenerated_prefix(self):
        # Regression test for the other bug fixed in commit 0a1f2ed:
        # insert_subtitle()'s ET round-trip used to serialize <dc:type> with
        # an auto-generated ns0:/ns1: prefix because nothing had called
        # ET.register_namespace("dc", ...) before the tree.write() inside
        # insert_subtitle(). Checked against the raw serialized text, not a
        # parsed tree -- ElementTree parsing resolves any prefix to the same
        # namespace URI regardless, so only the raw text reveals which
        # prefix string was actually written.
        self._migrate_one(self.meta_path)
        raw = self.meta_path.read_text(encoding="utf-8")
        self.assertIn("<dc:type>Text</dc:type>", raw)
        self.assertNotRegex(raw, r"<ns\d+:type>")

    def test_strips_stale_sibling_title_from_content_file(self):
        self._migrate_one(self.meta_path)
        content_root = ET.parse(self.xml_path).getroot()
        sibling_titles = [c for c in content_root if c.tag == f"{DB_NS}title"]
        self.assertEqual(sibling_titles, [])

    def test_carries_forward_title_from_old_dc_title_when_not_yet_migrated(self):
        # existing_title()'s other branch: a document that has never been
        # migrated yet still has the old <dc:title>, not a native <title>.
        self.meta_path.write_text(
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            '<info xmlns="http://docbook.org/ns/docbook" '
            'xmlns:dc="http://purl.org/dc/terms/" '
            'xmlns:xi="http://www.w3.org/2001/XInclude">\n'
            '  <dc:title>Not Yet Migrated</dc:title>\n'
            '  <xi:include href="../../common/shared-metadata.xml" />\n'
            '</info>\n',
            encoding="utf-8",
        )
        self._migrate_one(self.meta_path)
        root = ET.parse(self.meta_path).getroot()
        self.assertEqual(root.find(f"{DB_NS}title").text, "Not Yet Migrated")


if __name__ == "__main__":
    unittest.main()
