"""Generates docs/index.xml (the corpus's own DocBook table of contents,
per explicit direction: a scholarship document itself, not a lesser
navigational artifact) and docs/sitemap.xml, by walking the corpus's real
built state -- titles read from each document's own <info><title>, never
duplicated or hand-maintained. Regenerate whenever the corpus changes:
    python3 scripts/generate_index.py
"""
import subprocess
import sys
from pathlib import Path
from xml.etree import ElementTree as ET
from xml.sax.saxutils import escape as xml_escape

sys.path.insert(0, str(Path(__file__).resolve().parent))
from convert_to_docbook import (  # noqa: E402
    REPO_ROOT, DB_NS, write_metadata, build_html, validate,
)

DOCS_DIR = REPO_ROOT / "docs"
SITE_URL = "https://metavacua.github.io/legal-theory"

CATEGORY_ORDER = [
    ("court-record/matters", "Matters"),
    ("court-record/theory", "Theory"),
    ("cross-cutting", "Cross-Cutting"),
    ("proposals", "Proposals"),
    ("wip", "Works in Progress"),
    ("papers", "Papers"),
    ("bibliography", "Bibliography"),
]


def _shell_articles(docs_dir):
    for xml_path in sorted(Path(docs_dir).rglob("*.xml")):
        s = str(xml_path)
        if "/scratch/" in s or "/bibliography/entries/" in s or "/scripts/" in s:
            continue
        if xml_path.name.endswith(".meta.xml") or xml_path.name == "index.xml":
            continue
        root_tag = subprocess.run(
            ["xmllint", "--xpath", "name(/*)", str(xml_path)],
            capture_output=True, text=True,
        ).stdout.strip()
        if root_tag == "article":
            yield xml_path


def _title_for(xml_path):
    resolved = subprocess.run(
        ["xmllint", "--xinclude", str(xml_path)],
        capture_output=True, text=True, check=True,
    ).stdout
    root = ET.fromstring(resolved)
    info = root.find(f"{{{DB_NS}}}info")
    title_el = info.find(f"{{{DB_NS}}}title") if info is not None else None
    return title_el.text if title_el is not None and title_el.text else xml_path.stem


def _category_for(rel_path):
    rel_str = str(rel_path)
    for prefix, label in CATEGORY_ORDER:
        if rel_str.startswith(prefix + "/") or rel_str == prefix:
            return label
    return "Other"


def collect_documents():
    """[(relative_html_path, title, category), ...] sorted by category
    order then title -- the single source of truth both index.xml and
    sitemap.xml are built from."""
    docs = []
    for xml_path in _shell_articles(DOCS_DIR):
        rel = xml_path.relative_to(DOCS_DIR)
        title = _title_for(xml_path)
        category = _category_for(rel)
        html_rel = rel.with_suffix(".html")
        docs.append((html_rel, title, category))
    order_index = {label: i for i, (_, label) in enumerate(CATEGORY_ORDER)}
    docs.sort(key=lambda d: (order_index.get(d[2], len(CATEGORY_ORDER)), d[1]))
    return docs


def _anchor(label):
    return label.lower().replace(" ", "-")


def build_index_xml(docs, xml_path):
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<article xmlns="http://docbook.org/ns/docbook" '
        'xmlns:xi="http://www.w3.org/2001/XInclude" version="5.2" '
        'xml:id="index" xml:lang="en">',
        '  <xi:include href="index.meta.xml" />',
        '  <para>Generated index of every document in this corpus. '
        'Regenerated by <code>scripts/generate_index.py</code> -- do not hand-edit.</para>',
    ]
    by_category = {}
    for html_rel, title, category in docs:
        by_category.setdefault(category, []).append((html_rel, title))
    for _, label in CATEGORY_ORDER:
        entries = by_category.get(label)
        if not entries:
            continue
        lines.append(f'  <section xml:id="{_anchor(label)}">')
        lines.append(f'    <title>{xml_escape(label)}</title>')
        lines.append('    <itemizedlist>')
        for html_rel, title in entries:
            lines.append(
                f'      <listitem><para>'
                f'<link xlink:href="{xml_escape(str(html_rel))}" '
                f'xmlns:xlink="http://www.w3.org/1999/xlink">'
                f'{xml_escape(title)}</link></para></listitem>'
            )
        lines.append('    </itemizedlist>')
        lines.append('  </section>')
    lines.append('</article>')
    xml_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_sitemap(docs, sitemap_path):
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    lines.append(f"  <url><loc>{SITE_URL}/index.html</loc></url>")
    for html_rel, _, _ in docs:
        lines.append(f"  <url><loc>{SITE_URL}/{html_rel}</loc></url>")
    lines.append('</urlset>')
    sitemap_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    docs = collect_documents()
    meta_path = DOCS_DIR / "index.meta.xml"
    write_metadata(meta_path, "legal-theory — Index", subject="index")
    xml_path = DOCS_DIR / "index.xml"
    build_index_xml(docs, xml_path)
    errors = validate(xml_path)
    if errors:
        print(f"VALIDATION FAILED:\n" + "\n".join(errors), file=sys.stderr)
        return 1
    build_html(xml_path, DOCS_DIR / "index.html")
    build_sitemap(docs, DOCS_DIR / "sitemap.xml")
    print(f"Generated docs/index.xml + docs/index.html + docs/sitemap.xml "
          f"({len(docs)} documents indexed).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
